#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.
# chkconfig: 2345 90 10
# description: Redis is a persistent key-value database

PATH=/usr/local/bin:/sbin:/usr/bin:/bin

REDISPORT=9501
EXEC=/usr/local/php/bin/php
SERVER=/opt/cloudfog/web/cron/swoole.php

PIDFILE=/opt/cloudfog/web/cron/tmp/swoole-task.pid

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Swoole server..."
                $EXEC $SERVER start
        fi
        ;;

    stop)
        kill `cat $PIDFILE`
        if [ "$?" != 0 ] ; then
            echo " failed"
            exit 1
        else
            $EXEC $SERVER stop
            rm -f $PIDFILE
            echo " done"
        fi
        ;;

    restart)
        $0 stop
        $0 start
    ;;

    *)
        echo "Please use start or stop as first argument"
        ;;
esac
